liip_imagine:
    twig:
        mode: lazy

    loaders:
        default:
            filesystem:
                data_root: '%kernel.project_dir%/public'

    filter_sets:
        cache: ~
        thumb_recette:
            quality: 75            
            filters:
                thumbnail:
                    size: [612, 312]
                    mode: outbound
        header_recette:
            quality: 80
            format: webp
            filters:
                thumbnail:
                    size: [1200, 400]
                    mode: outbound
        profil_full:
            filters:
                relative_resize: { widen: 120 }
        form_preview:
            quality: 75
            filters:
                thumbnail:
                    size: [150, 150]
                    mode: outbound