liip_imagine:
    twig:
        mode: lazy

    loaders:
        default:
            filesystem:
                data_root: '%kernel.project_dir%/public'

    filter_sets:
        cache: ~
        
        # Utilisé sur les cartes (cards)
        thumb_recette:
            quality: 75
            format: webp
            filters:
                thumbnail:
                    size: [612, 312]
                    mode: outbound
        
        # Utilisé pour les bannières
        header_recette:
            quality: 80
            format: webp
            filters:
                thumbnail:
                    size: [1200, 400]
                    mode: outbound
        
        # Utilisé pour la photo de profil (corrigé pour Lighthouse)
        profil_full:
            quality: 75
            format: webp
            filters:
                thumbnail:
                    size: [120, 120]
                    mode: outbound
        
        # Utilisé dans les formulaires
        form_preview:
            quality: 75
            format: webp
            filters:
                thumbnail:
                    size: [150, 150]
                    mode: outbound